### ISSUE TITLE
Backtrace due to invalid projects

### ISSUE THREAD

**Issue by dolph** [dolph/next-review#15]
If you attempt to manually specify a project that doesn't exist, a backtrace occurs.

$ next-review asdf
Traceback (most recent call last):
  File ".../bin/next-review", line 9, in <module>
    load_entry_point('next-review==1.4.0', 'console_scripts', 'next-review')()
  File ".../next-review/next_review.py", line 316, in cli
    main(args)
  File ".../next-review/next_review.py", line 277, in main
    reviews = get_reviews(client, args.projects)
  File ".../next-review/next_review.py", line 63, in get_reviews
    if reviews[-1]['rowCount'] == 0:
KeyError: 'rowCount'

**Comment by dolph** [comment]
Fixed in dffb5e95fe571117706cbe794d2730a7bd98d1d4
