### ISSUE TITLE
'sortKey'  not in response returned by review.openstack.org

### ISSUE THREAD

**Issue by pozorvlak** [dolph/next-review#22]
When I run next-review, I get the error
```
Traceback (most recent call last):
  File "next_review.py", line 320, in <module>
    cli()
  File "next_review.py", line 316, in cli
    main(args)
  File "next_review.py", line 277, in main
    reviews = get_reviews(client, args.projects)
  File "next_review.py", line 58, in get_reviews
    query.append('resume_sortkey:%s' % reviews[-2]['sortKey'])
KeyError: 'sortKey'
```
It seems the resume_sortkey feature was removed in Gerrit 2.9: https://groups.google.com/forum/#!topic/repo-discuss/yQgRR5hlS3E.

**Comment by dolph** [comment]
Thanks for the heads up on this! I'll release a fixed version shortly.

**Comment by pozorvlak** [comment]
Thanks!
